kind: Deployment
apiVersion: apps/v1
metadata:
  name: gcp-filestore-csi-controller
spec:
  template:
    spec:
      containers:
        - $patch: delete
          name: csi-external-snapshotter
          image: registry.k8s.io/sig-storage/csi-snapshotter
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--timeout=300s"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
