apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-provisioner-prow-rc
imageTag:
  name: registry.k8s.io/sig-storage/csi-provisioner
  newTag: "v2.2.2"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-resizer-prow-rc
imageTag:
  name: registry.k8s.io/sig-storage/csi-resizer
  newTag: "v1.2.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-snapshotter-prow-rc
imageTag:
  name: registry.k8s.io/sig-storage/csi-snapshotter
  newTag: "v3.0.3"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-node-registrar-prow-rc
imageTag:
  name: registry.k8s.io/sig-storage/csi-node-driver-registrar
  newTag: "v2.2.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-gce-fs-driver-rc
imageTag:
  name: registry.k8s.io/cloud-provider-gcp/gcp-filestore-csi-driver
  newName: gcr.io/k8s-staging-cloud-provider-gcp/gcp-filestore-csi-driver
  newTag: "v1.0.0-rc1"
---
